### PR TITLE
Fix null warnings

### LINKED ISSUE #46: Fix warnings in data model
Builds and migrations warn about missing `required` keywords and number precision, and possible null references. This should be fixed.

### PR DESCRIPTION
**Pull request by MrFranQx**
This fixes the null warnings that display while compiling and migrating. Additionally, it gets rid of redundant null checks (probably not all are done though).

### CODE REVIEW

**Comment by MrFranQx** [comment]
closes #46

File: Booker/TagHelpers/UrlHandlerExtensions.cs [hunk 1]
```diff
@@ -18,6 +18,6 @@ public static string Handler(this IUrlHelper urlHelper, string handler, object?
             Values = routeValues
         });
 
-        return url;
+        return url ?? throw new ArgumentException("Invalid handler");
```
Comment (theluckyprogrammer) [inline Booker/TagHelpers/UrlHandlerExtensions.cs]:
```
 // Throw InvalidOperationException because the failure is due to the routing
 // configuration/state, not an invalid 'handler' argument itself.
 return url ?? throw new InvalidOperationException($"Could not find a route for the handler '{handler}'.");
```
Arguments seem to be fine; what is interesting is the way that the IUrlHelper method is handling unsuitable parameters.

File: Booker/Migrations/20250614175959_WarningFixes.cs
Comment (theluckyprogrammer) [inline Booker/Migrations/20250614175959_WarningFixes.cs:1]: We might reconsider how we seed data, we will need some seeding scripts to run as a MERGE ( Insert or Update ) command.

**Review by theluckyprogrammer — DISMISSED** [review]

File: Booker/Migrations/20250614175959_WarningFixes.cs
Comment (MrFranQx) [reply Booker/Migrations/20250614175959_WarningFixes.cs:1]: You're right, but we won't need these randomized seed data in production at all.
A solution that comes to my mind is to remove these from migrations and leave only the constant data (books, subjects, grades). Then, we may make a condition like this that runs on startup (pseudocode):
`if (isDevelopment() && _db.Items.Empty()) { seedData(); }`

File: Booker/TagHelpers/UrlHandlerExtensions.cs (hunk 1 above)
Comment (MrFranQx) [reply Booker/TagHelpers/UrlHandlerExtensions.cs]: Changed this in another way: every UrlHelper extension returns a nullable string, so I made this one do that as well. We don't need an exception at all now.

**Review by kowalczyk256 — APPROVED** [review]
Looks good to me
